src/CakeClub/Controllers/AdminController.cs
using CakeClub.Entities;
using CakeClub.Infrastructure.Services;
using CakeClub.Models.AdminViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace CakeClub.Controllers
{
    [Authorize(Roles="Administrator")]
    [Route("[controller]")]
    public class AdminController : Controller
    {
        private readonly SignInManager<User> _signInManager;
        private readonly EmailService _emailService;
        private readonly ILogger _logger;
        private readonly UserService _userService;

        public AdminController(
            SignInManager<User> signInManager,
            EmailService emailService,
            ILoggerFactory loggerFactory,
            UserService memberService,
            UserService userService)
        {
            _signInManager = signInManager;
            _emailService = emailService;
            _logger = loggerFactory.CreateLogger<AdminController>();
            _userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var members = await _userService.GetMembers();

            var model = new AdminIndexViewModel
            {
                Members = members
            };

            return View(model);
        }

        [HttpGet("[action]")]
        public async Task<IActionResult> EditMember(int id)
        {
            var member = await _userService.GetMember(id);

            var vm = new EditMemberViewModel
            {
                Member = member,
                IsAdmin = await _userService.IsAdministrator(member.Id)
            };

            return View(vm);
        }

        [HttpPost("[action]")]
        public async Task<IActionResult> EditMember(int id, EditMemberViewModel vm)
        {
            await _userService.UpdateMember(id, vm.Member);

            if (vm.IsAdmin)
            {
                await _userService.AddToAdministrators(vm.Member.Id);
            }
            else
            {
                await _userService.RemoveFromAdministrators(vm.Member.Id);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost("[action]")]
        public async Task<IActionResult> ResetMemberPassword(int id)
        {
            var member = await _userService.GetMember(id);

            if (string.IsNullOrEmpty(member.UserEmail)) return View("Error");

            await _userService.ResetPassword(member.UserEmail);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost("[action]")]
        public async Task<IActionResult> ActivateMember(int id)
        {
            await _userService.ActivateMember(id);
            
            return RedirectToAction(nameof(Index));
        }

        [HttpPost("[action]")]
        public async Task<IActionResult> DeactivateMember(int id)
        {
            await _userService.DeactivateMember(id);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("[action]")]
        public IActionResult Invite()
        {
            return View();
        }

        [HttpPost("[action]")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Invite(InviteViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _userService.Invite(model.Email);

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        #region Helpers

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

        #endregion
    }
}

src/CakeClub/Controllers/CakesController.cs
using AutoMapper.QueryableExtensions;
using CakeClub.Infrastructure;
using CakeClub.Infrastructure.Services;
using CakeClub.Models;
using CakeClub.Models.CakesViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CakeClub.Controllers
{
    [Authorize]
    [Route("[controller]")]
    public class CakesController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly VoteService _voteService;
        private readonly UserService _userService;
        private readonly UserProvider _userProvider;
        private readonly ILogger<CakesController> _logger;
        private readonly CakeService _cakeService;
        private readonly EmailService _emailService;

        public CakesController (ApplicationDbContext dbContext, UserService userService, UserProvider userProvider, VoteService voteService, CakeService cakeService, EmailService emailService, ILogger<CakesController> logger)
        {
            _dbContext = dbContext;
            _voteService = voteService;
            _userService = userService;
            _userProvider = userProvider;
            _cakeService = cakeService;
            _emailService = emailService;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var cakes = await _cakeService.GetCakes();

            var vm = new CakesViewModel();
            vm.Cakes = cakes;

            return View(vm);
        }

        [HttpGet("{cakeId}")]
        public async Task<IActionResult> Cake(int cakeId)
        {
            var cake = await _cakeService.GetCake(cakeId);
            var votes = await _cakeService.GetVotes(cakeId);

            var vm = new CakeViewModel();
            vm.Cake = cake;
            vm.Votes = votes;
            vm.HasVoted = await _voteService.HasCurrentMemberVoted(cakeId);

            return View(vm);
        }

        [HttpGet("[action]")]
        public async Task<IActionResult> CreateCake(DateTime? time = null)
        {
            var vm = new CreateCakeViewModel();

            if (time.HasValue)
                vm.Date = time.Value;
            else
                vm.Date = DateTime.Now;

            vm.Time = vm.Date.AddHours(13).AddMinutes(55);
            vm.Members = await _userService.GetActiveMembers();

            return View(vm);
        }

        [HttpPost("[action]")]
        public async Task<IActionResult> CreateCake(CreateCakeViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            var when = new DateTime(vm.Date.Year, vm.Date.Month, vm.Date.Day, vm.Time.Hour, vm.Time.Minute, 0);

            int id = await _cakeService.CreateCake(vm.Name, when, vm.Recipe, vm.BakeSelf, vm.VotesSent, vm.MemberId);

            var cake = await _cakeService.GetCake(id);

            await _emailService.SendCakeInvites(cake);

            return RedirectToAction(nameof(Cake), new { cakeId = id });
        }

        [HttpGet("{cakeId}/edit")]
        public async Task<IActionResult> EditCake(int cakeId)
        {
            var cake = await _cakeService.GetCake(cakeId);
            
            var vm = new EditCakeViewModel
            {
                CakeId = cake.Id,
                Name = cake.Name,
                Recipe = cake.Recipe,
                BakeSelf = cake.BakeSelf,
                Date = cake.EventTime,
                Time = cake.EventTime,
                MemberId = cake.CreatorId,
                Members = await _userService.GetActiveMembers()
            };

            return View(vm);
        }

        [HttpPost("{cakeId}/edit")]
        public async Task<IActionResult> EditCake(int cakeId, EditCakeViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            var when = new DateTime(vm.Date.Year, vm.Date.Month, vm.Date.Day, vm.Time.Hour, vm.Time.Minute, 0);
            await _cakeService.UpdateCake(cakeId, vm.Name, when, vm.Recipe, vm.BakeSelf, vm.MemberId);

            return RedirectToAction(nameof(Cake), new { cakeId = cakeId });
        }

        [HttpGet("{cakeId}/[action]")]
        [Authorize()]
        public async Task<IActionResult> AddVote(int cakeId)
        {
            var vm = new AddVoteViewModel
            {
                CakeId = cakeId
            };

            vm.Members = await _userService.GetActiveMembers();

            return View(vm);
        }

        [HttpPost("{cakeId}/[action]")]
        public async Task<IActionResult> AddVote(int cakeId, AddVoteViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            await _voteService.AddVote(vm.MemberId, cakeId, vm.Grade, vm.Participated);

            return RedirectToAction(nameof(Cake), new { cakeId = cakeId });
        }

        [HttpPost("{cakeId}/delete")]
        public async Task<IActionResult> DeleteCake(int cakeId)
        {
            var cake = await _cakeService.GetCake(cakeId);

            await _cakeService.DeleteCake(cakeId);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost("{cakeId}/uploadimage")]
        public async Task<IActionResult> UploadImage(int cakeId, ICollection<IFormFile> files)
        {
            return RedirectToAction(nameof(Cake), new { cakeId = cakeId });
        }

        [HttpPost("{cakeId}/startvote")]
        public async Task<IActionResult> StartVoting(int cakeId)
        {
            // Find all active members and send vote emails
            var members = await _userService.GetActiveMembers();

            foreach (var member in members)
            {
                await _voteService.SendVoteEmail(member.Id, cakeId);
            }

            return RedirectToAction("Cake", new { cakeId = cakeId });
        }

        [HttpGet("{cakeId}/vote")]
        public async Task<IActionResult> Vote(int cakeId)
        {
            var vm = new VoteViewModel();

            var currentMember = await _userProvider.GetCurrentMember();

            if (currentMember == null)
            {
                ModelState.AddModelError("", "An admin user cannot vote!");

                return View(vm);
            }

            if (await _dbContext.Votes.AnyAsync(x => x.Member.Id == currentMember.Id && x.Cake.Id == cakeId))
            {
                ModelState.AddModelError("", "You have already voted for this cake");

                return View(vm);
            }

            var cake = await _dbContext.Cakes.Where(x => x.Id == cakeId).ProjectTo<CakeDto>().FirstOrDefaultAsync();
            var member = await _dbContext.Members.Where(x => x.Id == currentMember.Id).ProjectTo<MemberDto>().FirstOrDefaultAsync();

            if (member == null)
            {
                ModelState.AddModelError("", "User not found");
            }

            if (cake == null)
            {
                ModelState.AddModelError("", "Cake not found");
            }

            vm.Member = member;
            vm.Cake = cake;
            vm.CakeId = cake.Id;
            vm.MemberId = currentMember.Id;

            return View(vm);
        }

        [HttpGet("/directvote")]
        [AllowAnonymous]
        public async Task<IActionResult> VoteDirectly(int cakeId, int memberId, string token, bool participated, int? grade = null)
        {
            if (!_voteService.Validate(memberId, cakeId, token))
            {
                return BadRequest("The provided token is invalid");
            }

            if (await _dbContext.Votes.AnyAsync(x => x.Member.Id == memberId && x.Cake.Id == cakeId))
            {
                return BadRequest("You have already voted for this cake");
            }

            var cake = await _dbContext.Cakes.Where(x => x.Id == cakeId).ProjectTo<CakeDto>().FirstOrDefaultAsync();
            var member = await _dbContext.Members.Where(x => x.Id == memberId).ProjectTo<MemberDto>().FirstOrDefaultAsync();

            if (member == null)
            {
                return BadRequest("Member not found");
            }

            if (cake == null)
            {
                return BadRequest("Cake not found");
            }

            await _voteService.Vote(memberId, cakeId, grade, participated);

            return RedirectToAction(nameof(Thanks), new { cakeId = cake.Id });
        }

        [HttpGet("/vote")]
        [AllowAnonymous]
        public async Task<IActionResult> VoteAnonymous(int cakeId, int memberId, string token)
        {
            var vm = new VoteViewModel();

            if (!_voteService.Validate(memberId, cakeId, token))
            {
                ModelState.AddModelError("", "The provided token is invalid");

                return View(nameof(Vote), vm);
            }

            if (await _dbContext.Votes.AnyAsync(x => x.Member.Id == memberId && x.Cake.Id == cakeId))
            {
                ModelState.AddModelError("", "You have already voted for this cake");

                return View(nameof(Vote), vm);
            }

            var cake = await _dbContext.Cakes
                .Where(x => x.Id == cakeId)
                .ProjectTo<CakeDto>()
                .FirstOrDefaultAsync();
            
            var member = await _dbContext.Members
                .Where(x => x.Id == memberId)
                .ProjectTo<MemberDto>()
                .FirstOrDefaultAsync();

            if (member == null)
            {
                ModelState.AddModelError("", "User not found");
            }

            if (cake == null)
            {
                ModelState.AddModelError("", "Cake not found");
            }

src/CakeClub/Controllers/StatisticsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using CakeClub.Entities;
using CakeClub.Infrastructure;
using CakeClub.Models.StatisticsViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using CakeClub.Models;
using System.Collections.Generic;
using AutoMapper.QueryableExtensions;

namespace CakeClub.Controllers
{
    [Authorize]
    public class StatisticsController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<User> _userManager;
        private readonly ILogger<StatisticsController> _logger;

        public StatisticsController (UserManager<User> userManager, ILogger<StatisticsController> logger, ApplicationDbContext dbContext)
        {
            _userManager = userManager;
            _logger = logger;
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            var cakesWithGrade = await _dbContext.Cakes
                .ProjectTo<CakeDto>()
                .ToListAsync();

            var members = await _dbContext.Members.ToListAsync();

            int totalWeeks = 0;
            if (cakesWithGrade.Any())
            {
                var firstCake = cakesWithGrade.Min(x => x.EventTime);
                var hoursSinceFirstCake = (DateTime.Now - firstCake).TotalHours;
                totalWeeks = Convert.ToInt32(Math.Floor(hoursSinceFirstCake / 24 / 7));
            }

            var currentRankings = (from c in cakesWithGrade
                                   where c.CreatorActive && c.Grade.HasValue
                                   group c by c.CreatorId into g
                                   select g.OrderByDescending(x => x.EventTime).FirstOrDefault())
                                   .OrderByDescending(cake => cake.Grade)
                                   .ToList();

            var model = new IndexViewModel
            {
                ActiveMembers = members.Count(member => member.Active),
                TotalMembers = members.Count,
                TotalCakes = cakesWithGrade.Count,
                TotalWeeks = Convert.ToInt32(totalWeeks),
                RankedCakes = cakesWithGrade.Count(cake => cake.Grade.HasValue),
                AverageCakeGrade = cakesWithGrade.Average(cake => cake.Grade),
                TopCakeGrade = cakesWithGrade.Max(cake => cake.Grade),
                LowestCakeGrade = cakesWithGrade.Min(cake => cake.Grade),
                CurrentRankings = currentRankings
            };

            return View(model);
        }

        public async Task<IActionResult> AllCakes()
        {
            var allCakes = await _dbContext.Cakes
                .ProjectTo<CakeDto>()
                .ToListAsync();

            return View(allCakes);
        }
    }
}

src/CakeClub/Views/Shared/_Layout.cshtml
@inject SignInManager<User> SignInManager
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Cake Club</title>

        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <link rel="stylesheet" href="~/css/fullcalendar.min.css" />
        <link rel="stylesheet" href="~/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/css/fontawesome-stars.css" />
        <link rel="stylesheet" href="~/css/pikaday.min.css" />
        <link rel="stylesheet" href="~/css/cakeclub.css" />
        <link rel="stylesheet" href="~/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/theme.bootstrap_4.min.css" />
        <link rel="stylesheet" href="~/css/jquery.datetimepicker.min.css" />
        <script src="~/js/jquery-3.2.1.min.js"></script>
        <script src="~/js/jquery.barrating.min.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="container-fluid">
                <nav class="navbar navbar-toggleable-sm navbar-light bg-faded">
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" asp-action="Index" asp-controller="Home">CakeClub</a>
                    <div class="collapse navbar-collapse" id="navbar">
                        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-item nav-link" asp-controller="Home" asp-action="Upcoming">Upcoming</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-item nav-link" asp-controller="Cakes" asp-action="Index">Calendar</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-item nav-link" asp-controller="Statistics" asp-action="Index">Statistics</a>
                                </li>
                            }
                            @if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="adminDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Administration</a>
                                    <div class="dropdown-menu" aria-labelledby="adminDropdown">
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="Invite">Send Invite</a>
                                    </div>
                                </li>
                            }
                        </ul>
                        @await Html.PartialAsync("_LoginPartial")
                    </div>
                </nav>
            </div>
            <div class="container-fluid" style="margin: 20px auto auto auto">
                @RenderBody()
            </div>
        </div>
        <!--<footer class="footer">
            <i>Gifs are from <a href="http://www.pusheen.com">Pusheen</a> © 2010 - 2015.</i>
        </footer>-->

        <script src="~/js/jquery.validate.min.js"></script>
        <script src="~/js/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/jquery.tablesorter.min.js"></script>
        <script src="~/js/jquery.tablesorter.widgets.min.js"></script>
        <script src="~/js/jquery.datetimepicker.full.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/moment-with-locales.min.js"></script>
        <script src="~/js/fullcalendar.min.js"></script>
        <script src="~/js/vue.min.js"></script>
        <script src="~/js/lodash.min.js"></script>
        <script src="~/js/pikaday.min.js"></script>
        <script src="~/js/site.js"></script>

        @RenderSection("scripts", required: false)
    </body>

</html>